### ISSUE TITLE
List management has two input and submit

### ISSUE THREAD

**Issue by jeena** [CampDev/Tasky#1] opened 2013-07-31 20:22 UTC
When I click on the list management icon (which wasn't really clear hat I would manage lists there), I have 2 input fields to add a new list with two submit buttons but in different design.
![screenshot from 2013-07-31 22 21 29](https://f.cloud.github.com/assets/151764/889458/ea576e3e-fa1e-11e2-8d78-87b144347512.png)

**Comment by CampDev** [comment] 2013-07-31 20:25
That's what happens when you're testing with lists and tasks. Seems to be easy to solve though. We'll solve that in 1.0.1. :)

**Comment by CampDev** [comment] 2013-08-01 08:23
Jeena, can you please let me know if it's fixed now? Deleting all of my lists would be a bit troublesome seeing how many tasks I have. :p

**Comment by jeena** [comment] 2013-08-01 09:35
Now there is only the first one there with the short submit button "Submit Qu"

**Comment by Cacauu** [comment] 2013-08-04 15:20
So the issue is fixed and the thing from Issue #4 is to be fixed.

**Comment by Nygu** [comment] 2013-09-06 07:34
Should say "Add list" now.

**Closed as completed by Nygu** 2013-09-06 07:34 UTC
